version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.10.0
jobs:
  npm_install_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  docker_build_push_image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Build docker image from Dockerfile
          command: docker build -t resume-as-a-service:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push resume-as-a-service:latest

workflows:
  dev:
    jobs:
      - npm_install_and_test:
          filters:
            branches:
              only: dev
      - docker_build_push_image:
          requires:
            - npm_install_and_test
          filters:
            branches:
              only: dev
  master:
    jobs:
      - npm_install_and_test:
          filters:
            branches:
              only: master
      - docker_build_push_image:
          requires:
            - npm_install_and_test
          filters:
            branches:
              only: master
