version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.3.0
jobs:
  npm_install_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  check_and_build_only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: domojesse/resume-as-a-service

workflows:
  dev:
    jobs:
      - check_and_build_only
      - docker/publish:
          requires:
            - check_and_build_only
          image: domojesse/resume-as-a-service
          tag: 'latest,dev'
  master:
    jobs:
      - npm_install_and_test:
          filters:
            branches:
              only: master
